### ISSUE TITLE
Trigger plug-in manually

### ISSUE THREAD

**Issue by mathaefele** [rdicosmo/updateswh#14]
Currently, the plug-in is activated only when the browser is on a page whose URL is of the form gitlab.* or gitea.* or if the URL pattern is stored in the preference.
Would that be possible to manually trigger the plug-in from the plug-in menu with an additional button `Activate plug-in` on top of the two existing ones `Instructions` and `Settings` ?

It would then make the little floppy disk to appear and store the URL pattern in the settings for a later visit.

**Comment by rdicosmo** [comment]
Thanks for the suggestion. This functionality is now implemented in 0.6.6
