### ISSUE TITLE
Button turning red after a couple of uses

### ISSUE THREAD

**Issue by pierrepo** [rdicosmo/updateswh#2]
After several uses of the extension, the button becomes red when pressed.

Firefox developer tools show this error message:
```
POST
https://archive.softwareheritage.org/api/1/origin/save/git/url/https://github.com/jupyter/security/
429 (Too Many Requests)
```

It would be useful to have a pop-up message warning the user that the maximum number of API requests has been reached and that he/she should wait xx minutes before using the extension again.

**Comment by rdicosmo** [comment]
Closing this, as it is resolved in the latest version 0.5.0
