### ISSUE TITLE
Injection of the embedded FontAwesome in the widget font family stomps on the one defined by webpages

### ISSUE THREAD

**Issue by olasd** [rdicosmo/updateswh#9]
Hi,

When using a website that uses a `FontAwesome` font family (for instance, ArgoCD), the version injected by updateswh overrides that of the website, even when the domain of the page is not in the "known forges" list.

Please consider
 - only injecting DOM elements on webpages in known domains
 - injecting the FontAwesome font family under a non-conflictual name (e.g. one prefixed with `updateswh`)

**Comment by rdicosmo** [comment]
May you suggest a patch?

**Comment by barais** [comment]
I confirm the bug. I will see if I can propose a patch. Extension currently breaks the layout of https://correctexam.github.io/corrigeExamFront/

**Comment by rdicosmo** [comment]
Thanks @barais, looking forward to the patch!

**Comment by barais** [comment]
Wait before merging please. Still one issue to solve with my two last commits

**Comment by barais** [comment]
PR #17 can be tested and merged if it is ok. 
Current code use fontawesome just to draw five icons. The current PR, removes dependencies to https://fontawesome.com/ v4 and replaces the icons with the swg version of the same icons.
